export const MERMAID_CONFIG: any = {
    startOnLoad: true,
/*    theme: mermaidAPI.Theme.Base,
    logLevel: mermaidAPI.LogLevel.Info,
    securityLevel: mermaidAPI.SecurityLevel.Strict,*/
    arrowMarkerAbsolute: true,
    flowchart: {
        htmlLabels: true,
        curve: "linear",
    },
    sequence: {
        diagramMarginX: 50,
        diagramMarginY: 10,
        actorMargin: 50,
        width: 150,
        height: 65,
        boxMargin: 10,
        boxTextMargin: 5,
        noteMargin: 10,
        messageMargin: 35,
        mirrorActors: true,
        bottomMarginAdj: 1,
        useMaxWidth: true,
        rightAngles: true,
    },
    gantt: {
        titleTopMargin: 25,
        barHeight: 20,
        barGap: 4,
        topPadding: 50,
        leftPadding: 75,
        gridLineStartPadding: 35,
        fontSize: 11,
        fontFamily: '"Open-Sans", "sans-serif"',
        numberSectionStyles: 4,
        axisFormat: "%Y-%m-%d",
    },
}
