name: Unit tests

on:
  push:

jobs:
  unit_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    container: golang:1.18-alpine
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add build-base; cd ./go; go install
      - name: Unit tests
        run: cd ./go; go test -v ./...
        timeout-minutes: 2
