name: tests

on:
  push:
jobs:
  run_test:
    name: "Run tests"
    runs-on: ubuntu-latest
    container: golang
    steps:
      - uses: actions/checkout@v2
      - id: run_tests
      - run: go test -v ./...
      - timeout-minutes: 2
